main_app/urls.py
# main_app/urls.py
from django.urls import path
from . import views

app_name = 'movies' 

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    # Other URL patterns here
    path('about/', views.about, name='about'),
    path('movies/', views.movie_index, name='movie_index'),
    path('movies/<int:movie_id>/', views.movie_details, name='movie_details'),
    path('movies/create/', views.MovieCreate.as_view(), name='movie_create'),
    path('movies/<int:pk>/update/', views.MovieUpdate.as_view(), name='movie_update'),
    path('movies/<int:pk>/delete/', views.MovieDelete.as_view(), name='movie_delete'),
    path('movies/<int:movie_id>/add-character/', views.add_character, name='add-character'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='movies:home'), name='logout'),
]

moviecollector/urls.py
from django.contrib import admin
from django.urls import path ,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
Genders =(
    ('M','Male'),
    ('F','Female'),
)
# Create your models here
class Movie(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=100)
    release_date = models.DateField(max_length=100)
    genre = models.CharField(max_length=50,null='Unknown')
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('movie_detail', args=[str(self.id)])
    
class Characters(models.Model):
        name = models.CharField(max_length=100)
        gender = models.CharField(
            max_length=50,
            choices=Genders,
            default='M',
        )
        movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
        def __str__(self):
            return f"{self.get_gender_display()} on {self.name}"
        
        class Meta:
            ordering = ['name']
   

main_app/forms.py
from django import forms
from .models import Characters

class CharactersForm(forms.ModelForm):
    class Meta:
        model = Characters
        fields = ['name', 'gender']
        widgets = {
            'name': forms.TextInput(
            attrs={
                'placeholder': 'Enter character name',
                'type': 'text',
            }
            ),
        }

main_app/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Movie
from django.urls import reverse
from .forms import CharactersForm
from django.shortcuts import redirect
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from django.contrib.auth.views import LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login
# Create your views here.
class Home(LoginView):
    template_name = 'home.html'

class Log(LogoutView):
    template_name = 'home.html'


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def movies(request):
    return render(request, 'movies.html')

@login_required
def movie_index(request):
    movies = Movie.objects.filter(user=request.user)
    return render(request, 'movies/index.html', {'movies': movies})

def movie_details(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    characters_form = CharactersForm()
    return render(request, 'movies/details.html', {'movie': movie , 'characters_form': characters_form})
def movie_create(request):
    return render(request, 'movies/create.html')

def add_character(request, movie_id):
    form = CharactersForm(request.POST)
    if form.is_valid():
        new_character = form.save(commit=False)
        new_character.movie_id = movie_id
        new_character.save()
        return redirect('movies:movie_details', movie_id=movie_id)
    
def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request, user)
            return redirect('movies:movie_index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

class MovieCreate(LoginRequiredMixin,CreateView):
    model = Movie
    fields = ['title', 'description', 'release_date', 'genre']
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('movies:movie_details', kwargs={'movie_id': self.object.id})

class MovieUpdate(UpdateView):
    model = Movie
    fields = ['title', 'description', 'release_date', 'genre']
    def get_success_url(self):
        return reverse('movies:movie_details', kwargs={'movie_id': self.object.id})

class MovieDelete(DeleteView):
    model = Movie
    success_url = '/movies/'
    def get_success_url(self):
        return reverse('movies:movie_index')

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <h1>About the Movie Collector</h1>
    <hr />
    <p class="page-content">
        The Movie Collector is a web application designed to help users manage their movie collections. 
    </p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="" />
    <title>Movie Collector</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />

    {% block head %}
    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <img src="{% static 'css/images/icon.png' %}" alt="The Movie Collector Logo" />
          <h1>The Movie Collector</h1>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
            <li><a href="/movies">All Movies</a></li>
            <li><a href="/movies/create">Add Movie</a></li>
            <li>
              <form id="logout-form" method="post" action="{% url 'movies:logout' %}">
                {% csrf_token %}
                <button type="submit">Log out</button>
              </form>
            </li>    
            <li><a href="{% url 'movies:about' %}">About</a></li>
      
            {% else %}
            <li><a href="{% url 'movies:movie_index' %}">Login</a></li>  
            <li><a href="{% url 'movies:signup' %}">Sign Up</a></li>
            <li><a href="{% url 'movies:about' %}">About</a></li>
            {% endif %}

        </ul>
      </nav>
    </header>
    <main>
     {% block content %} 
     {% endblock %}
     </main>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link
  rel="stylesheet"
  href="{% static 'css/home.css' %}"
/>
{% endblock %}

{% block content %}
<section class="logo-container">
  <div class="movie-container">
    <img
      src="{% static 'css/images/Movie.jpg' %}"
      alt="The Movie Collector Logo"
    />
  </div>
</section>
{% if not user.is_authenticated %}
<section>
  <form action="{% url 'movies:login' %}" method="post" class="login">
    <h1>Login</h1>
    {% csrf_token %} {{ form.as_p }}
    <button type="submit" class="btn submit">Login</button>
  </form>
</section>
{% endif %}

{% endblock %}

main_app/templates/main_app/movie_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Movie?</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>

<h2>Are you sure you want to delete {{ movie.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'movies:movie_details' movie.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/movie_form.html
{% extends 'base.html' %}

{% block content %}

<!-- Page Header to indicate whether we're adding or editing a movie -->
<div class="page-header">
  {% if movie %}
    <h1>Edit {{ movie.title }}</h1>
  {% else %}
    <h1>Add a New Movie 🎬</h1>
  {% endif %}
</div>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save Movie</button>
</form>

<a href="{% url 'movies:movies' %}">← Back to Movie List</a>

{% endblock %}

main_app/templates/movies/create.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}

<div class="page-header">
  <h1>Add a Movie</h1>
</div>

<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/movies/details.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/movies/movie-detail.css' %}" />
{% endblock %} 
{% block content %}
<section class="cat-container">
  <div class="cat-img">
    <img src="{% static 'images/sk8r-boi-cat.svg' %}" alt="A skater boy cat" />
  </div>
  <div class="cat-details">
    <h1>{{ movie.title }}</h1>
    <h2>Genre: {{ movie.genre }}</h2>
    <h2>Release Year: {{ movie.release_date }}</h2>
    {% if movie.image_url %}
      <img src="{{ movie.image_url }}" alt="{{ movie.title }} Poster" class="usr-img">
    {% endif %}
    <p>{{ movie.description }}</p>
    <div class="cat-actions">
      <a href="{% url 'movies:movie_update' movie.id %}" class="btn warn">Edit</a>
      <a href="{% url 'movies:movie_delete' movie.id %}" class="btn danger">Delete</a>
    </div>
  </div>
</section>
<h3>Add a Characters</h3>
<!-- Add just above the feedings table -->
<form method="post" action="{% url 'movies:add-character' movie.id %}" class="subsection-content" autocomplete="off">
  {% csrf_token %} 
  {{ characters_form.as_p }}
  <button type="submit" class="btn submit">Add Characters</button>
</form>

<!-- Existing cat-container above -->
<div class="feedings-toy-container">
  <section class="feedings">
    <div class="subsection-title">
      <h2>Characters</h2>
      <img
        src="{% static 'images/cat-cone.svg' %}"
        alt="An ice cream cone cat"
      />
      <img src="{% static 'images/cat-onigiri.svg' %}" alt="A cat as onigiri" />
      <img
        src="{% static 'images/kitty-kabob.svg' %}"
        alt="A kabob of kittens"
      />
    </div>
    {% if movie.characters_set.all.count %}

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Gender</th>
        </tr>
      </thead>
      <tbody>
        {% for Characters in movie.characters_set.all %}
          <tr>
            <td>{{Characters.name}}</td>
            <td>{{Characters.get_gender_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {%else %}
    <div class="subsection-content">
      <p> No characters added yet.</p>
      </div>
    {% endif %}
  </section>
</div>


{% endblock %}

main_app/templates/movies/index.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/movies/movie-index.css' %}">
{% endblock %} 
{% block content %}
<h1>🎬 Movie List</h1>

<div class="card-container">
  {% for movie in movies %}
    <div class="card">
      <a href="/movies/{{movie.id}}">
        {% if movie.image_url %}
          <img src="{{ movie.image_url }}" alt="{{ movie.title }} Poster" class="usr-img">
        {% endif %}
        <div class="card-content">
          <h2>{{ movie.title }} ({{ movie.year }})</h2>
          <p><strong>Genre:</strong> {{ movie.genre }}</p>
          <p>{{ movie.description }}</p>
        </div>
      </a>
    </div>
  {% endfor %}
</div>
{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  <!-- <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" /> -->
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}